export const DEFAULT_TASK_LIST = [
    {
        id: '1',
        title: 'Test pertama',
        task: 'Lakukan Seperti Video ini',
        note: 'Lorem Ipsum dan lain lain',
        attact: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        icon: 'ri-walk-line',
        finish: true,
        finishDate: '2020-17-14',
        createdAt: '2020-17-14',
        updatedAt: '2020-17-14',
    },
    {
        id: '2',
        title: 'Test kedia',
        task: 'Lakukan Seperti gambar ini',
        note: 'Lorem Ipsum dan lain lain asdasdas',
        attact: 'https://moewalls.com/wp-content/uploads/2023/01/ushio-noa-blue-archive-thumb-728x410.jpg',
        icon: 'ri-run-line',
        finish: false,
        finishDate: null,
        createdAt: '2020-17-14',
        updatedAt: '2020-17-14',
    },
    {
        id: '3',
        title: 'Test Ketiga',
        task: 'Lakukan Seperti gambar ini',
        note: 'Lorem Ipsum dan lain lain asdasdas',
        attact: null,
        icon: 'ri-home-smile-line',
        finish: false,
        finishDate: null,
        createdAt: '2020-17-14',
        updatedAt: '2020-17-14',
    },
]